version: "3.4"
services:
  db:
    image: cloudacademydevops/insecurewebapp-db:v1
    build:
      context: ./backend
      dockerfile: Dockerfile.db
    ports:
      - 5432:5432
    networks:
      insecurewebapp:

  api:
    image: cloudacademydevops/insecurewebapp-api:v1
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    ports:
      - 8080:8080
    links:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cloudacademy
      - POSTGRES_CONNSTR=jdbc:postgresql://db:5432/cloudacademy?ssl=true&sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory
    depends_on:
      - db
    networks:
      insecurewebapp:

  frontend:
    image: cloudacademydevops/insecurewebapp-frontend:v1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - api
    environment:
      - REACT_APP_APIHOSTPORT=api:8080
    depends_on:
      - api
    networks:
      insecurewebapp:

networks:
  insecurewebapp:
    driver: bridge