name: Insecure Web App

on:
  push:
    tags:
      - '1.*.*'
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    # FRONTEND
    - name: Frontend - install NPM dependencies
      run: |
        cd ./frontend
        npm install
        npm run build
        tar -czf release-${{ env.RELEASE_VERSION }}.tar.gz build

    # BACKEND
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean package spring-boot:repackage --file ./backend/pom.xml

    # ARTIFACTS
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-${{ env.RELEASE_VERSION }}
        path: | 
          ./frontend/release-${{ env.RELEASE_VERSION }}.tar.gz
          ./backend/target/webapp-insecure-1.0-SNAPSHOT.jar

    # RELEASE
    - name: Make Release
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: release-${{ env.RELEASE_VERSION }}
        files: |
          ./frontend/release-${{ env.RELEASE_VERSION }}.tar.gz
          ./backend/target/webapp-insecure-1.0-SNAPSHOT.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}